from pid import PidController
a = PidController(20, 1, 0, 0)
a.setKP(0.5)
print a.getPower(15)
print a.getPower(18)
print a.getPower(21)
print a.getPower(24)
print a.getPower(21)
print a.getPower(18)
print a.getPower(24)
print a.getPower(26)
print a.getPower(20)
print a.getPower(20)
print a.getPower(19)
print a.getPower(17)
print a.getPower(15)
print a.getPower(13)
print a.getPower(11)
print a.getPower(9)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)
# print a.getPower(20)